/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import Information.BscThesis;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Irana
 */
public class BscThesisPage extends javax.swing.JFrame {

    /**
     * Creates new form BscThesisPage
     */
    private BscThesis t;

    /**
     * if visitor is normal person:k=0; if visitor is owner of thesis:k=1; if
     * visitor is supervisor:k=2; if visitor is head of department:k=3;
     *
     * @param t
     * @param k
     */
    public BscThesisPage(BscThesis t, int k) {
        initComponents();
        this.t = t;
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int) (d.getWidth() - this.getWidth()) / 2, (int) (d.getHeight() - this.getHeight()) / 2);
        txt_id.setText(t.get_Id() + "");
        txt_id.setEditable(false);
        txt_ownerName.setText(t.get_stdName());
        txt_ownerName.setEditable(false);
        txt_ownerfield.setText(t.get_stdField());
        txt_ownerfield.setEditable(false);
        txt_jurorName.setText(t.get_jurorName());
        txt_jurorName.setEditable(false);
        txt_supervisorName.setText(t.get_donName());
        txt_supervisorName.setEditable(false);
        txt_location.setText(t.get_location());
        txt_location.setEditable(false);
        if (t.get_date() != null) {
            txt_time.setText(t.get_date().toString());
        } else {
            txt_time.setText("Not set");
        }
        txt_time.setEditable(false);
        txt_topic.setText(t.get_topic());
        txt_topic.setEditable(false);
        txt_summary.setText(t.get_summary());
        txt_summary.setEditable(false);
        if (t.get_status() == 0) {
            txt_status.setText("Pending approval by the supervisor");
        } else if (t.get_status() == 1 && t.get_jurorId() == null) {
            txt_status.setText("Pending appointment of the referee");
        } else if (t.get_status() == -1) {
            txt_status.setText("Rejected by the supervisor");
        } else if (t.get_status() == 1 && t.get_jurorId() != null && t.get_location().equals("Not Set")) {
            txt_status.setText("Waiting for appointment of time and place");
        } else if (t.get_status() == 1 && t.get_jurorId() != null && !(t.get_location().equals("Not Set"))) {
            txt_status.setText("Invitation sent");
        }
        txt_status.setEditable(false);
        if (t.get_stdName2() == null) {
            lab_ownerName2.setVisible(false);
            lab_ownerField2.setVisible(false);
            txt_ownerName2.setVisible(false);
            txt_ownerField2.setVisible(false);
        } else {
            txt_ownerName2.setText(t.get_stdName2());
            txt_ownerName2.setEditable(false);
            txt_ownerField2.setText(t.get_stdField2());
            txt_ownerField2.setEditable(false);
        }
        switch (k) {
            case 0:
                combo_action.setVisible(false);
                lab_warning.setVisible(false);
                btn_continue.setVisible(false);
                break;
            case 1:
                if (t.get_location().equals("Not Set") && !(t.get_jurorName().equals("Not Set")) && t.get_status() == 1) {
                    combo_action.addItem("Determine the time and place");
                    break;
                } else {
                    combo_action.setVisible(false);
                    lab_warning.setVisible(false);
                    btn_continue.setVisible(false);
                    break;
                }
            case 2:
                if (t.get_status() == 1) {
                    combo_action.setVisible(false);
                    lab_warning.setVisible(false);
                    btn_continue.setVisible(false);
                    break;
                } else if (t.get_status() == 0 || t.get_status() == -1) {
                    combo_action.addItem("Approve");
                    combo_action.addItem("Do not approve");
                    break;
                }
            case 3:
                if (t.get_jurorName().equals("Not Set") && t.get_status() == 1) {
                    combo_action.addItem("Determine the referee");
                    break;
                } else {
                    combo_action.setVisible(false);
                    lab_warning.setVisible(false);
                    btn_continue.setVisible(false);
                    break;
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lab_warning = new javax.swing.JLabel();
        combo_action = new javax.swing.JComboBox();
        btn_continue = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_id = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ownerName = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_ownerfield = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_jurorName = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_supervisorName = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        txt_location = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        txt_time = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        txt_status = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        txt_topic = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        txt_summary = new javax.swing.JTextArea();
        lab_ownerField2 = new javax.swing.JLabel();
        lab_ownerName2 = new javax.swing.JLabel();
        txt_ownerName2 = new javax.swing.JTextField();
        txt_ownerField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText(" Student and Personnel Automation of Isfahan University");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Thesis ID:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Owner Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Owner Field:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Supervisor Name:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Juror Name:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Place Of Defense:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Time Of Defense:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Status:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("Topic:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Summary:");

        lab_warning.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lab_warning.setForeground(new java.awt.Color(255, 0, 51));
        lab_warning.setText("Please choose action:");

        combo_action.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combo_action.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please choose" }));

        btn_continue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_continue.setText("Continue");
        btn_continue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_continueMouseClicked(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane1.setViewportView(txt_id);

        txt_ownerName.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane2.setViewportView(txt_ownerName);

        txt_ownerfield.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane3.setViewportView(txt_ownerfield);

        txt_jurorName.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane4.setViewportView(txt_jurorName);

        txt_supervisorName.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane5.setViewportView(txt_supervisorName);

        txt_location.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane13.setViewportView(txt_location);

        txt_time.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane14.setViewportView(txt_time);

        txt_status.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane15.setViewportView(txt_status);

        txt_topic.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane16.setViewportView(txt_topic);

        txt_summary.setColumns(20);
        txt_summary.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_summary.setRows(5);
        jScrollPane17.setViewportView(txt_summary);

        lab_ownerField2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lab_ownerField2.setText("Owner Field2:");

        lab_ownerName2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lab_ownerName2.setText("Owner Name2:");

        txt_ownerName2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        txt_ownerField2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane15))
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane17)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4)))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lab_ownerName2)
                                            .addComponent(lab_ownerField2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_ownerName2)
                                            .addComponent(txt_ownerField2))
                                        .addGap(79, 79, 79))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(lab_warning)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo_action, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_continue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lab_warning)
                        .addComponent(combo_action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_back)
                        .addComponent(btn_continue))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_ownerName2)
                            .addComponent(txt_ownerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_ownerField2)
                            .addComponent(txt_ownerField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_continueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continueMouseClicked
        // TODO add your handling code here:
        try {
            if (combo_action.getSelectedItem().equals("Approve")) {
                Client.os.writeInt(4);
                Client.os.flush();
                Client.os.writeInt(t.get_Id());
                Client.os.flush();
                Client.os.writeInt(1);
                Client.os.flush();
                if (Client.is.readBoolean()) {
                    JOptionPane.showMessageDialog(this, "The defense request was successfully approved", "successfully", JOptionPane.INFORMATION_MESSAGE);
                    t.authenticate1(1);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "This service is not  available now", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else if (combo_action.getSelectedItem().equals("Do not approve")) {
                Client.os.writeInt(4);
                Client.os.flush();
                Client.os.writeInt(t.get_Id());
                Client.os.flush();
                Client.os.writeInt(2);
                Client.os.flush();
                if (Client.is.readBoolean()) {
                    JOptionPane.showMessageDialog(this, "The defense request was rejected successfully", "successfully", JOptionPane.INFORMATION_MESSAGE);
                    t.authenticate1(-1);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "This service is not  available now", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else if (combo_action.getSelectedItem().equals("Determine the time and place")) {
                this.dispose();
                SetTimeAndLocation st = new SetTimeAndLocation(t);
                st.setVisible(true);
                st.setAlwaysOnTop(true);
            } else if (combo_action.getSelectedItem().equals("Determine the referee")) {
                this.dispose();
                SetJuror sj = new SetJuror(1, t);
                sj.setVisible(true);
                sj.setAlwaysOnTop(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_continueMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_continue;
    private javax.swing.JComboBox combo_action;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lab_ownerField2;
    private javax.swing.JLabel lab_ownerName2;
    private javax.swing.JLabel lab_warning;
    private javax.swing.JTextPane txt_id;
    private javax.swing.JTextPane txt_jurorName;
    private javax.swing.JTextPane txt_location;
    private javax.swing.JTextField txt_ownerField2;
    private javax.swing.JTextPane txt_ownerName;
    private javax.swing.JTextField txt_ownerName2;
    private javax.swing.JTextPane txt_ownerfield;
    private javax.swing.JTextPane txt_status;
    private javax.swing.JTextArea txt_summary;
    private javax.swing.JTextPane txt_supervisorName;
    private javax.swing.JTextPane txt_time;
    private javax.swing.JTextPane txt_topic;
    // End of variables declaration//GEN-END:variables
}
