/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import Information.BscThesis;
import Information.Student;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Irana
 */
public class RegisterBscThesis extends javax.swing.JFrame {

    /**
     * Creates new form RegisterBscThesis
     */
    private Student s, s2;
    private String supId;
    private boolean f1 = false, f2 = true, f3 = false;

    public RegisterBscThesis(Student s1) {
        initComponents();
        s = s1;
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int) (d.getWidth() - this.getWidth()) / 2, (int) (d.getHeight() - this.getHeight()) / 2);
        this.setTitle("Register Thesis");
        txt_ownerName2.setEditable(false);
        txt_ownerField2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lab_supervisor = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_supervisorId = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        txt_topic = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        txt_summary = new javax.swing.JTextArea();
        lab_ownerField2 = new javax.swing.JLabel();
        lab_ownerName2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_ownerName2 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_ownerField2 = new javax.swing.JTextPane();
        btn_register = new javax.swing.JButton();
        btn_supervisorSearch = new javax.swing.JButton();
        btn_ownerIdSearch = new javax.swing.JButton();
        lab_ownerId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ownerId2 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        lab_topic = new javax.swing.JLabel();
        lab_supervisorName = new javax.swing.JLabel();
        lab_summary = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText(" Student and Personnel Automation of Isfahan University");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));

        lab_supervisor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lab_supervisor.setText("Supervisor ID:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("Topic:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Summary:");

        btn_back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        txt_supervisorId.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane5.setViewportView(txt_supervisorId);

        txt_topic.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jScrollPane16.setViewportView(txt_topic);

        txt_summary.setColumns(20);
        txt_summary.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_summary.setRows(5);
        jScrollPane17.setViewportView(txt_summary);

        lab_ownerField2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lab_ownerField2.setText("Owner Field2:");

        lab_ownerName2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lab_ownerName2.setText("Owner Name2:");

        jScrollPane6.setViewportView(txt_ownerName2);

        jScrollPane7.setViewportView(txt_ownerField2);

        btn_register.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_register.setText(" register");
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registerMouseClicked(evt);
            }
        });

        btn_supervisorSearch.setText("?");
        btn_supervisorSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_supervisorSearchMouseClicked(evt);
            }
        });

        btn_ownerIdSearch.setText("?");
        btn_ownerIdSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ownerIdSearchMouseClicked(evt);
            }
        });

        lab_ownerId.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lab_ownerId.setText("Owner ID2:");

        jScrollPane1.setViewportView(txt_ownerId2);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText(" If this thesis is done by two students fill this field. Otherwise, leave this blank.");

        lab_topic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_topic.setForeground(new java.awt.Color(255, 0, 51));
        lab_topic.setText("*");

        lab_supervisorName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_supervisorName.setForeground(new java.awt.Color(255, 0, 51));
        lab_supervisorName.setText("*");

        lab_summary.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_summary.setForeground(new java.awt.Color(255, 0, 51));
        lab_summary.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane17)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lab_topic)
                                        .addGap(84, 84, 84)
                                        .addComponent(btn_register)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lab_supervisor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lab_supervisorName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_supervisorSearch)))
                                .addGap(0, 13, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_summary))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(lab_ownerId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(lab_ownerName2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(lab_ownerField2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_ownerIdSearch)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_back)
                        .addComponent(btn_register)
                        .addComponent(lab_topic))
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_supervisor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_supervisorSearch)
                        .addComponent(lab_supervisorName)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_ownerId)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_ownerIdSearch)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_ownerName2)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_ownerField2))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lab_summary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        StudentThesisSystem sts = new StudentThesisSystem(s);
        sts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_supervisorSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supervisorSearchMouseClicked
        // TODO add your handling code here:
        if (txt_supervisorId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Starred fields should not be empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Client.os.writeInt(6);
                Client.os.flush();
                Client.os.writeObject(txt_supervisorId.getText());
                Client.os.flush();
                if (Client.is.readBoolean()) {
                    JOptionPane.showMessageDialog(this, "supervisor finded :)", "Find", JOptionPane.INFORMATION_MESSAGE);
                    supId = txt_supervisorId.getText();
                    txt_supervisorId.setText((String) Client.is.readObject());
                    txt_supervisorId.setEditable(false);
                    lab_supervisor.setText("Supervisor Name:");
                    f1 = true;
                    btn_supervisorSearch.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "this ID is not correct", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_supervisorSearchMouseClicked

    private void btn_ownerIdSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ownerIdSearchMouseClicked
        // TODO add your handling code here:
        if (txt_ownerId2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "If this thesis is done by two students fill this field. Otherwise, leave this blank.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Client.os.writeInt(10);
                Client.os.flush();
                Client.os.writeObject(txt_ownerId2.getText());
                Client.os.flush();
                if (Client.is.readBoolean()) {
                    JOptionPane.showMessageDialog(this, "Student finded :)", "Find", JOptionPane.INFORMATION_MESSAGE);
                    s2 = (Student) Client.is.readObject();
                    txt_ownerId2.setEditable(false);
                    txt_ownerName2.setText(s2.get_name() + " " + s2.get_lastname());
                    txt_ownerField2.setText(s2.get_field());
                    f2 = true;
                    f3 = true;
                    btn_ownerIdSearch.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "this ID is not correct", "ERROR", JOptionPane.ERROR_MESSAGE);
                    f2 = false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_ownerIdSearchMouseClicked

    private void btn_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseClicked
        // TODO add your handling code here:
        if (txt_ownerId2.getText().isEmpty()) {
            f2 = true;
        }
        if (txt_topic.getText().isEmpty() || !f1 || !f2 || txt_summary.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Starred fields should not be empty and  If this thesis is done by single student leave field owner ID2 blank.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!f3) {
                BscThesis bs = new BscThesis(s.get_name() + " " + s.get_lastname(), s.get_Id(), s.get_field(), txt_topic.getText(), txt_summary.getText(), txt_supervisorId.getText(), supId);
                try {
                    Client.os.writeInt(11);
                    Client.os.flush();
                    Client.os.writeObject(bs);
                    Client.os.flush();
                    bs.set_Id(Client.is.readInt());
                    s.add_thesis(bs);
                    JOptionPane.showMessageDialog(this, "Thesis added successfully :) .we sent your request to supervisor for approve.", "Find", JOptionPane.INFORMATION_MESSAGE);
                    StudentThesisSystem sts = new StudentThesisSystem(s);
                    sts.setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            } else {
                BscThesis bs2 = new BscThesis(s.get_name() + " " + s.get_lastname(), s.get_Id(), s.get_field(), s2.get_name() + " " + s2.get_lastname(), s2.get_Id(), s2.get_field(), txt_topic.getText(), txt_summary.getText(), txt_supervisorId.getText(), supId);
                try {
                    Client.os.writeInt(11);
                    Client.os.flush();
                    Client.os.writeObject(bs2);
                    Client.os.flush();
                    bs2.set_Id(Client.is.readInt());
                    s.add_thesis(bs2);
                    JOptionPane.showMessageDialog(this, "Thesis added successfully :) .we sent your request to supervisor for approve.", "Find", JOptionPane.INFORMATION_MESSAGE);
                    StudentThesisSystem sts = new StudentThesisSystem(s);
                    sts.setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btn_registerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_ownerIdSearch;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_supervisorSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lab_ownerField2;
    private javax.swing.JLabel lab_ownerId;
    private javax.swing.JLabel lab_ownerName2;
    private javax.swing.JLabel lab_summary;
    private javax.swing.JLabel lab_supervisor;
    private javax.swing.JLabel lab_supervisorName;
    private javax.swing.JLabel lab_topic;
    private javax.swing.JTextPane txt_ownerField2;
    private javax.swing.JTextPane txt_ownerId2;
    private javax.swing.JTextPane txt_ownerName2;
    private javax.swing.JTextArea txt_summary;
    private javax.swing.JTextPane txt_supervisorId;
    private javax.swing.JTextPane txt_topic;
    // End of variables declaration//GEN-END:variables
}
