/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import Information.MscThesis;
import Information.PhdThesis;
import Information.Thesis;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Irana
 */
public class SetJuror extends javax.swing.JFrame {

    /**
     * Creates new form SetJuror
     */
    //if Bscthesis,kind=1,if Mscthesis,kind=2,if Phdthesis,kind=3;
    private int kind, ID;
    private String jId1, jId2, jId3;
    private boolean f1 = false, f2 = false, f3 = false;
    private Thesis thes;

    public SetJuror(int k, Thesis t) {
        initComponents();
        kind = k;
        ID = t.get_Id();
        thes=t;
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int) (d.getWidth() - this.getWidth()) / 2, (int) (d.getHeight() - this.getHeight()) / 2);
        this.setTitle("Set Juror");
        if (kind == 1) {
            lab_jurorId2.setVisible(false);
            txt_jurorId2.setVisible(false);
            lab_jurorId2_.setVisible(false);
            btn_jurorId2.setVisible(false);
            lab_jurorId3.setVisible(false);
            txt_jurorId3.setVisible(false);
            lab_jurorId3_.setVisible(false);
            btn_jurorId3.setVisible(false);
        } else if (kind == 2) {
            lab_jurorId3.setVisible(false);
            txt_jurorId3.setVisible(false);
            lab_jurorId3_.setVisible(false);
            btn_jurorId3.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lab_jurorId = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        lab_jurorId_ = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        lab_jurorId2 = new javax.swing.JLabel();
        lab_jurorId3 = new javax.swing.JLabel();
        lab_jurorId2_ = new javax.swing.JLabel();
        lab_jurorId3_ = new javax.swing.JLabel();
        btn_jurorId = new javax.swing.JButton();
        btn_jurorId2 = new javax.swing.JButton();
        btn_jurorId3 = new javax.swing.JButton();
        txt_jurorId1 = new javax.swing.JTextField();
        txt_jurorId2 = new javax.swing.JTextField();
        txt_jurorId3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText(" Student and Personnel Automation of Isfahan University");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        lab_jurorId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_jurorId.setForeground(new java.awt.Color(255, 255, 0));
        lab_jurorId.setText("Juror ID:");

        btn_ok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
        });

        lab_jurorId_.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_jurorId_.setForeground(new java.awt.Color(255, 0, 51));
        lab_jurorId_.setText("*");

        btn_back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_back.setText("BACK");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        lab_jurorId2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_jurorId2.setForeground(new java.awt.Color(255, 255, 0));
        lab_jurorId2.setText("Juror ID2:");

        lab_jurorId3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_jurorId3.setForeground(new java.awt.Color(255, 255, 0));
        lab_jurorId3.setText("Juror ID3:");

        lab_jurorId2_.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_jurorId2_.setForeground(new java.awt.Color(255, 0, 51));
        lab_jurorId2_.setText("*");

        lab_jurorId3_.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lab_jurorId3_.setForeground(new java.awt.Color(255, 0, 51));
        lab_jurorId3_.setText("*");

        btn_jurorId.setText("?");
        btn_jurorId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jurorIdMouseClicked(evt);
            }
        });

        btn_jurorId2.setText("?");
        btn_jurorId2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jurorId2MouseClicked(evt);
            }
        });

        btn_jurorId3.setText("?");
        btn_jurorId3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jurorId3MouseClicked(evt);
            }
        });

        txt_jurorId1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_jurorId2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_jurorId3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lab_jurorId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_jurorId1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_jurorId_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_jurorId))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btn_back)
                        .addGap(39, 39, 39)
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lab_jurorId2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_jurorId2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lab_jurorId3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_jurorId3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lab_jurorId3_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_jurorId3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lab_jurorId2_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_jurorId2)))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_jurorId)
                        .addComponent(txt_jurorId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_jurorId_)
                        .addComponent(btn_jurorId)))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_jurorId2)
                        .addComponent(txt_jurorId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_jurorId2_)
                        .addComponent(btn_jurorId2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_jurorId3)
                        .addComponent(txt_jurorId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_jurorId3_)
                        .addComponent(btn_jurorId3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(btn_back))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
        // TODO add your handling code here:
        if (kind == 1) {
            if (f1) {
                try {
                    Client.os.writeInt(7);
                    Client.os.flush();
                    Client.os.writeInt(1);
                    Client.os.flush();
                    Client.os.writeInt(ID);
                    Client.os.flush();
                    Client.os.writeObject(jId1);
                    Client.os.flush();
                    thes.set_jurorId(jId1);
                    thes.set_jurorName(txt_jurorId1.getText());
                    JOptionPane.showMessageDialog(this, "The juror was set successfully :)", "successful", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "This service is not  available now", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Starred fields should not be empty or incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (kind == 2) {
            if (f1 && f2) {
                try {
                    Client.os.writeInt(7);
                    Client.os.flush();
                    Client.os.writeInt(2);
                    Client.os.flush();
                    Client.os.writeInt(ID);
                    Client.os.flush();
                    Client.os.writeObject(jId1);
                    Client.os.flush();
                    Client.os.writeObject(jId2);
                    Client.os.flush();
                    thes.set_jurorId(jId1);
                    thes.set_jurorName(txt_jurorId1.getText());
                    ((MscThesis)thes).set_jurorId2(jId2);
                    ((MscThesis)thes).set_jurorName2(txt_jurorId2.getText());
                    JOptionPane.showMessageDialog(this, "The jurors was set successfully :)", "successful", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "This service is not  available now", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Starred fields should not be empty or incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (f1 && f2 && f3) {
                try {
                    Client.os.writeInt(7);
                    Client.os.flush();
                    Client.os.writeInt(3);
                    Client.os.flush();
                    Client.os.writeInt(ID);
                    Client.os.flush();
                    Client.os.writeObject(jId1);
                    Client.os.flush();
                    Client.os.writeObject(jId2);
                    Client.os.flush();
                    Client.os.writeObject(jId3);
                    Client.os.flush();
                    thes.set_jurorId(jId1);
                    thes.set_jurorName(txt_jurorId1.getText());
                    ((PhdThesis)thes).set_jurorId2(jId2);
                    ((PhdThesis)thes).set_jurorName2(txt_jurorId2.getText());
                    ((PhdThesis)thes).set_jurorId3(jId3);
                    ((PhdThesis)thes).set_jurorName3(txt_jurorId3.getText());
                    JOptionPane.showMessageDialog(this, "The jurors was set successfully :)", "successful", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "This service is not  available now", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Starred fields should not be empty or incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_okMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_jurorIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jurorIdMouseClicked
        // TODO add your handling code here:
        if (txt_jurorId1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Starred fields should not be empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Client.os.writeInt(6);
                Client.os.flush();
                Client.os.writeObject(txt_jurorId1.getText());
                Client.os.flush();
                if (Client.is.readBoolean()) {
                    String t2=(String) Client.is.readObject();
                    jId1 = txt_jurorId1.getText();
                    txt_jurorId1.setText(t2);
                    txt_jurorId1.setEditable(false);
                    lab_jurorId.setText("Juror Name:");
                    f1 = true;
                    btn_jurorId.setVisible(false);
                    JOptionPane.showMessageDialog(this, "juror finded :)", "Find", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "this ID is not correct", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btn_jurorIdMouseClicked

    private void btn_jurorId2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jurorId2MouseClicked
        // TODO add your handling code here:
        if (txt_jurorId2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Starred fields should not be empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Client.os.writeInt(6);
                Client.os.flush();
                Client.os.writeObject(txt_jurorId2.getText());
                Client.os.flush();
                if (Client.is.readBoolean()) {
                    JOptionPane.showMessageDialog(this, "juror finded :)", "Find", JOptionPane.INFORMATION_MESSAGE);
                    jId2 = txt_jurorId2.getText();
                    txt_jurorId2.setText((String) Client.is.readObject());
                    txt_jurorId2.setEditable(false);
                    lab_jurorId2.setText("Juror Name:");
                    f2 = true;
                    btn_jurorId2.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "this ID is not correct", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btn_jurorId2MouseClicked

    private void btn_jurorId3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jurorId3MouseClicked
        // TODO add your handling code here:
        if (txt_jurorId3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Starred fields should not be empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Client.os.writeInt(6);
                Client.os.flush();
                Client.os.writeObject(txt_jurorId3.getText());
                Client.os.flush();
                if (Client.is.readBoolean()) {
                    JOptionPane.showMessageDialog(this, "juror finded :)", "Find", JOptionPane.INFORMATION_MESSAGE);
                    jId3 = txt_jurorId3.getText();
                    txt_jurorId3.setText((String) Client.is.readObject());
                    txt_jurorId3.setEditable(false);
                    lab_jurorId3.setText("Juror Name:");
                    f3 = true;
                    btn_jurorId3.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "this ID is not correct", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Server Not Find.", "ERROR", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btn_jurorId3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_jurorId;
    private javax.swing.JButton btn_jurorId2;
    private javax.swing.JButton btn_jurorId3;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lab_jurorId;
    private javax.swing.JLabel lab_jurorId2;
    private javax.swing.JLabel lab_jurorId2_;
    private javax.swing.JLabel lab_jurorId3;
    private javax.swing.JLabel lab_jurorId3_;
    private javax.swing.JLabel lab_jurorId_;
    private javax.swing.JTextField txt_jurorId1;
    private javax.swing.JTextField txt_jurorId2;
    private javax.swing.JTextField txt_jurorId3;
    // End of variables declaration//GEN-END:variables
}
